alibaba/pont

src/compiler.ts
fixed generate Map error to 'defs.Map' error
=> [fix] generate Map error

src/compiler.ts, src/generate.ts
pont-config.json
```json
{
"originUrl": "http://localhost:8080/api-docs-fix.json",
"outDir": "test/api/creditmanager",
"templatePath": "./pontTemplate.ts"
}
```
=> fix: 使用 mkdirpSync 自动创建生成目录

README.md
更新readme, 添加 nuxt-ts-pont-demo
=> doc: add nuxt-ts-pont-demo

README.md, package.json, src/cmd.ts, src/manage.ts, yarn.lock
=> feat: add check cmd

package.json, src/manage.ts, src/scripts/base.ts, src/scripts/index.ts, src/scripts/swagger.ts, src/translate.ts, src/utils.ts, test/test.ts
=> feat: add scripts adapter

package.json, src/compiler.ts, src/scripts/swagger.ts, src/standard.ts, yarn.lock
修复 issue：[https://github.com/alibaba/pont/issues/49](https://github.com/alibaba/pont/issues/49)。
部分参数包含 -，应该用引号包含
测试已通过
=> fix: fix param key

yarn.lock
yarn.lock中目前master代码锁的是alibaba的npm源, 根据package-lock.json生成了yarn.lock, 后续考虑移除package-lock.json, 只维护一份yarn.lock
=> 根据package-lock.json生成yarn.lock

README.md
添加 @nestjs/swagger 生成 pont 文件时没有 mods 的解决方法
=> 添加 @nestjs/swagger 相关 FAQ

.vscode/launch.json, README.md, src/compiler.ts, src/scripts/index.ts, src/scripts/swagger.ts, src/standard.ts, test/fixtures/open-api.json
=> Swagger V3 支持

packages/pont-vscode-plugin/src/utils.ts
Pont plugin will read pont-engine version in project package.json instead of reading local node_modules pont-engine dependency's version only
=> Change pont-engine version installed by pont plugin

packages/pont-core/package.json, packages/pont-core/src/manage.ts, packages/pont-vscode-plugin/package.json, packages/pont-vscode-plugin/yarn.lock
=> 修复一个仅配置original通过all同步导致的bug

packages/pont-vscode-plugin/yarn.lock
replace package registry of alibaba.inc
=> chore: use yarnpkg registry

packages/pont-core/src/scripts/swagger.ts
=> fix: works without tags on swagger json

packages/pont-core/src/generators/generate.ts, packages/pont-core/test/fixtures/api-docs.json
支持tag中以 / 或者 . 作为分隔符, 方便多版本接口设计
服务端定义
@ApiUseTags('/v1/users')  或者 @ApiUseTags('v1.users')
@Controller('/v1/users')
export class UserController  {
@Post()
@ApiOperation({ title: '创建一个新用户并返回用户id', operationId: 'createUser' })
@ApiCreatedResponse({ description: '用户创建成功!', type: String })
async createUser(@Body() data: CreateUserDto) {
return await this.userService.createUser(data);
}
}
客户端调用
API.v1.users.createUser.request(...)
=> 支持tags中存在多级命名空间

packages/pont-engine/src/diff.ts, packages/pont-engine/src/standard.ts
=> Fix context undefined

.vscode/launch.json, packages/pont-engine/src/standard.ts
=> Fix vscode launch

package.json, packages/pont-engine/package.json, packages/pont-engine/src/standard.ts
添加`npm run watch`来执行`lerna run watch`, 省去开两个终端
=> Feat 添加`npm run watch`来执行`lerna run watch`, 省去开两个终端

README.md
=> feat: update qrcode

packages/pont-engine/src/standard.ts
=> fix: update surrounding

README.md, packages/pont-engine/src/utils.ts
一点点优化, `fetchMethodPath` 修正为相对 `process.cwd`, 这样配置的时候自定义 `fetchMethod` 路径更加容易理解
与master 测试结果一致
=> fetchMethodPath 优化为相对 process.cwd() 路径

packages/pont-engine/src/generators/generate.ts, packages/pont-engine/src/manage.ts
- [ √ ] Bugfix(修正错误)
- [ √ ] Yes(是)
- [ √ ] All tests are passing(所有测试都通过)
=> fix: 多origin时只更新当前origin接口信息

packages/pont-engine/package.json, yarn.lock
=> chore: update prettier version to fixes #238

README.md
=> update readme for @nestjs/swagger v4 usage

packages/vscode-pont/src/mocks.ts
修复vscode插件 快捷键 pont.refreshMocks 异常报错的问题
默认快捷键`ctrl+command+M` 正常刷新或生成.mocks/mocks.ts文件
=> fix(vscode-pont): 修复refresh mocks data 异常报错的问题 fixes #204

packages/pont-engine/src/manage.ts, packages/pont-engine/src/utils.ts
=> feat(pont-engine): 更新Mod时关联更新bo（BaseClass）

README.md, packages/pont-engine/src/generators/generate.ts, packages/pont-engine/src/manage.ts, packages/pont-engine/src/utils.ts, packages/vscode-pont/configSchema.json
=> feat(all): 新增配置spiltApiLock(是否拆分api-lock.json,默认关闭)便于用户平滑升级

packages/pont-engine/src/manage.ts, packages/pont-engine/src/utils.ts, packages/vscode-pont/src/UI.ts, packages/vscode-pont/src/utils.ts
=> feat(pont-engine vscode-pont): 1.添加vscode插件代码块模板 2.工具栏底部添加呼出查询接口UI的快捷方式

README.md, packages/pont-engine/src/cmd.ts, packages/pont-engine/src/generators/generate.ts, packages/pont-engine/src/manage.ts, packages/pont-engine/src/scan.ts, packages/pont-engine/src/standard.ts, packages/pont-engine/src/utils.ts, packages/vscode-pont/src/UI.ts
=> 重构scan命令,支持其他通用用法

README.md
=> docs(readme): pont scan 生成的应该是 unusedRequests.json 文件

packages/vscode-pont/src/commands/index.ts, packages/vscode-pont/tsconfig.json
=> feat: 添加注释

packages/pont-engine/src/generators/generate.ts, packages/pont-engine/src/manage.ts, packages/pont-engine/src/scripts/start.ts, packages/vscode-pont/package.json, packages/vscode-pont/src/views/pontOrigins.ts
=> fix(pontorigins.ts): 修复不存在配置时,文件名展示为undefined

README.md
=> fix: 修复文档错误

packages/pont-engine/src/scripts/swagger.ts
=> fix: 修复 SwaggerV3  parameters 里 typeName 为空的问题

packages/pont-engine/src/scripts/swagger.ts
=> fix: 🐛 修复 swagger V2 转换标准数据时，enum 数据丢失的问题

packages/vscode-pont/src/commands/index.ts
=> fix(commands/index.ts): 修复基类更新后,列表没有刷新的问题

packages/pont-engine/src/scripts/swagger.ts
```json
{
"get": {
"tags": [
"User"
],
"description": "分页",
"operationId": "page",
"parameters": [
{
"name": "size",
"in": "query",
"required": true,
"schema": {
"type": "integer",
"description": "页大小",
"format": "int64"
}
},
{
"name": "current",
"in": "query",
"required": true,
"schema": {
"type": "integer",
"description": "页码",
"format": "int64"
}
},
{
"name": "orders",
"in": "query",
"required": false,
"schema": {
"type": "array",
"description": "排序字段，数据库字段名",
"items": {
"$ref": "#/components/schemas/OrderItem"
}
}
}
],
"responses": {
"200": {
"description": "OK",
"content": {
"*/*": {
"schema": {
"$ref": "#/components/schemas/PageUserEntity"
}
}
}
}
}
}
}
```
上面的 orders 参数应该解析成 …
=> fix: SwaggerV3 无法解析 query 参数中的嵌套对象

packages/pont-engine/src/scripts/swagger.ts
=> fix: parameters 的参数名称取值错误

packages/pont-engine/src/utils/templateHelp.ts, packages/vscode-pont/package.json
=> fix: 完善template编译路径

packages/pont-engine/src/main/originManage/index.ts
=> fix: 修复远程数据源解析失败时,diff问题

packages/pont-engine/src/compatible/generators/generate.ts, packages/pont-engine/src/main/Config.ts, packages/pont-engine/src/main/Manager.ts, packages/vscode-pont/src/commands/index.ts, packages/vscode-pont/src/mocks.ts, packages/vscode-pont/src/utils/index.ts
=> fix: 修复 mock 问题

packages/pont-engine/src/compatible/generators/generate.ts
=> fix: 修复 modName 导出问题

packages/pont-engine/src/compatible/standard.ts
=> feat: 修复对DataSource或者BassClass DataType扩展无效的问题

packages/pont-engine/src/main/Config.ts
=> fix: origin 配置中的 originType 属性被覆盖

packages/pont-engine/src/compatible/generators/generate.ts
=> fix: 修复类型未引入问题

packages/pont-engine/src/constants/index.ts, packages/pont-engine/src/main/Manager.ts, packages/pont-engine/src/utils/PontFileManager.ts, packages/pont-engine/src/utils/translate.ts
=> fix: 修复翻译失败问题

packages/pont-engine/src/utils/templateHelp.ts
=> fix(pont-engine): 修复存在多个pont-config时模板之间相互覆盖的问题

packages/pont-engine/src/utils/templateHelp.ts
=> fix(pont-engine): 修复模板路径读取错误的问题

docs/pontConfig.md, packages/pont-engine/package.json, packages/pont-engine/src/compatible/Config.ts, packages/pont-engine/src/compatible/scripts/base.ts, packages/pont-engine/src/main/Config.ts, packages/pont-engine/src/main/originManage/OriginReader.ts, packages/pont-engine/src/types/pontConfig.ts, packages/pont-engine/src/utils/translate.ts, packages/vscode-pont/configSchema.json, yarn.lock
=> feat: add some translate engines

packages/pont-engine/src/utils/translate.ts
=> fix: fix translate import error

packages/pont-engine/src/utils/translate.ts
=> fix:  baidu translate not work

packages/vscode-pont/src/mocks.ts
=> fix: 解决mocks文件中跳出死循环逻辑导致的接口返回空对象的问题

packages/vscode-pont/src/commands/index.ts
=> fix: 修复重置时mock数据不更新问题

packages/vscode-pont/src/mocks.ts
=> fix: 修复mocks文件中分页数据不符合预期的问题

packages/pont-engine/src/compatible/scripts/swagger.ts, packages/pont-engine/src/compiler/swagger/SwaggerV2.ts, packages/pont-engine/src/compiler/swagger/SwaggerV3.ts
=> fix: #182 swaggerV2根元素无tags时，mod生成失败

packages/pont-engine/src/compatible/generators/generate.ts
=> fix: #378 修复surrounding为typeScript时不生成pontCore的问题

packages/pont-engine/src/compatible/scripts/swagger.ts, packages/pont-engine/src/compiler/swagger/SwaggerV2.ts, packages/pont-engine/src/compiler/swagger/SwaggerV3.ts
=> feat: use tags in operation-object when global tags is empty #390 #403

packages/pont-engine/src/compatible/scripts/swagger.ts
=> fix: #391 枚举包含数值时，生成的类型声明重复

packages/pont-engine/src/compatible/scripts/swagger.ts, packages/pont-engine/src/compiler/swagger/SwaggerV2.ts, packages/pont-engine/src/compiler/swagger/SwaggerV3.ts, packages/pont-engine/src/constants/defaultModule.ts
1. 默认模块抽取为常量
2. 完善生成api默认tag的逻辑
3. 修复重复生成默认的swagger tag导致生成重复接口模块的问题
=> fix generating duplicate modules

docs/pontConfig.md, packages/pont-engine/src/compatible/Config.ts, packages/pont-engine/src/compatible/scripts/base.ts, packages/pont-engine/src/main/Config.ts, packages/pont-engine/src/main/originManage/OriginReader.ts, packages/pont-engine/src/types/pontConfig.ts, packages/pont-engine/src/utils/PontFileManager.ts, packages/pont-engine/src/utils/translate.ts, packages/vscode-pont/configSchema.json
=> feat: #394 支持自定义翻译文件的生成路径

packages/pont-engine/package.json
=> chore: improve pont-engine package.json

packages/pont-engine/src/compatible/standard.ts
=> fix(pont-engine): 修复ObjectMap类型错误生成为defs.xxx.ObjectMap的问题

README.md, yarn.lock
=> fix yarn.lock and README error
